### ISSUE TITLE
Exclude admin and signature directories from sitemap

### ISSUE THREAD

**Issue by bitroniq** [bitroniq/bitroniq.github.io#59]
Change the configuration to exclude admin and signature directories from sitemap.

```yml
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "admin/*"
    values:
      sitemap:  false
  - scope:
      path: "signature/*"
    values:
      sitemap:  false
```
