### ISSUE TITLE
Obfuscate email address

### ISSUE THREAD

**Issue by bitroniq** [bitroniq/bitroniq.github.io#6]
Use a very simple combination of CSS and jQuery which displays the email address correctly to the user and also works when the anchor is clicked or hovered:

HTML:
```html
<a href="mailto:me@example.spam" id="lnkMail">moc.elpmaxe@em</a>
```
CSS:
```css
#lnkMail {
    unicode-bidi: bidi-override;
    direction: rtl;
}
```
jQuery:
```js
$('#lnkMail').hover(function(){
    // here you can use whatever replace you want
    var newHref = $(this).attr('href').replace('spam', 'com');
    $(this).attr('href', newHref);
});
```

Example: [https://jsfiddle.net/qy1dkkbh/](https://jsfiddle.net/qy1dkkbh/)
